services:
  api:
    build: .
    working_dir: /app/Backend
    command: uvicorn main:app --host 0.0.0.0 --port 8000
    ports:
      - "8000:8000"
    restart: unless-stopped

  ui:
    build: .
    working_dir: /app/Backend
    command: python app.py
    ports:
      - "7860:7860"
    environment:
      API_SINGLE_URL: http://api:8000/predict
      API_BATCH_URL: http://api:8000/predict_batch
    depends_on:
      - api
    restart: unless-stopped
